#!/usr/bin/env python3
"""
Generate publication-standard figures for "FinalVersion.tex" from the
CORRECTED data.

Data source: analysis_v2/dta/ (produced by analysis_v2/build_analysis.py from
the vendored WITS extracts in data/wits_raw/). Fully self-contained.
Output: figures/pub_*.pdf (vector), as included by FinalVersion.tex.

The figures backed by corrected trade data are produced here:
 - trade flows, trade balance, balance ratio,
 - export composition, import composition, structural-shift (2023 reversal),
 - China import penetration.
The China/Russia/EU comparison figures are generated by
analysis_v2/build_import_partners.py because they use the split all-partner
import extracts.
"""
import os
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DTA = os.path.join(REPO, "analysis_v2", "dta")
OUT = os.path.join(REPO, "figures")

# ---- publication style ------------------------------------------------------
plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "DejaVu Serif"],
    "font.size": 11,
    "axes.titlesize": 11,
    "axes.labelsize": 11,
    "legend.fontsize": 9.5,
    "xtick.labelsize": 9.5,
    "ytick.labelsize": 9.5,
    "axes.linewidth": 0.8,
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
})
# Grayscale palette: figures must remain legible in black-and-white printing.
NAVY = "#303030"
RED = "#6f6f6f"
GRAY = "#9a9a9a"
COVID = (2020, 2022)


def style_ax(ax, ylabel, xlabel="Year"):
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_ylabel(ylabel)
    ax.set_xlabel(xlabel)
    ax.grid(axis="y", color="#d9d9d9", linewidth=0.6, zorder=0)
    ax.set_axisbelow(True)


def covid_band(ax):
    ax.axvspan(COVID[0] - 0.4, COVID[1] + 0.4, color="#000000", alpha=0.05, zorder=0)


def save(fig, name):
    fig.savefig(os.path.join(OUT, name + ".pdf"))
    plt.close(fig)
    print("wrote", name)


t = pd.read_stata(os.path.join(DTA, "kazakhstan_china_annual_trade_panel_2015_2024.dta"))
yr = t["year"].values

# ---- 1. trade flows ---------------------------------------------------------
fig, ax = plt.subplots(figsize=(7, 4.2))
covid_band(ax)
ax.plot(yr, t.exports_bn, color=NAVY, lw=2.0, marker="o", ms=4, label="Exports to China")
ax.plot(yr, t.imports_bn, color=RED, lw=2.0, ls="--", marker="s", ms=4, label="Imports from China")
ax.plot(yr, t.total_trade_bn, color=GRAY, lw=1.3, ls=":", marker="^", ms=3.5, label="Total trade")
style_ax(ax, "US\\$ billions")
ax.set_xticks(yr)
ax.set_ylim(0, None)
ax.legend(frameon=False, loc="upper left")
save(fig, "pub_trade_flows")

# ---- 2. trade balance (bars) -----------------------------------------------
fig, ax = plt.subplots(figsize=(7, 4.2))
covid_band(ax)
colors = [NAVY if v >= 0 else RED for v in t.trade_balance]
ax.bar(yr, t.trade_balance, color=colors, width=0.62, zorder=3)
ax.axhline(0, color="black", lw=0.8)
style_ax(ax, "Trade balance (US\\$ billions)")
ax.set_xticks(yr)
ax.set_ylim(t.trade_balance.min() - 1.0, t.trade_balance.max() + 0.8)
for x, v in zip(yr, t.trade_balance):
    ax.annotate(f"{v:+.1f}", (x, v), textcoords="offset points",
                xytext=(0, 4 if v >= 0 else -12), ha="center", va="top" if v < 0 else "bottom",
                fontsize=7.5, color="#333")
save(fig, "pub_trade_balance")

# ---- 3. balance ratio -------------------------------------------------------
fig, ax = plt.subplots(figsize=(7, 4.2))
covid_band(ax)
ax.plot(yr, t.balance_ratio, color=NAVY, lw=2.0, marker="o", ms=4)
ax.axhline(0, color="black", lw=0.8)
ax.fill_between(yr, t.balance_ratio, 0, where=t.balance_ratio >= 0, color=NAVY, alpha=0.10)
ax.fill_between(yr, t.balance_ratio, 0, where=t.balance_ratio < 0, color=RED, alpha=0.12)
style_ax(ax, "Balance ratio, (X − M) / (X + M)")
ax.set_xticks(yr)
save(fig, "pub_balance_ratio")

# ---- composition (shares) ---------------------------------------------------
s = pd.read_stata(os.path.join(DTA, "kazakhstan_china_sectoral_trade_2015_2024.dta"))
s = s[s.year.between(2015, 2024)]


def composition(flow_col, keep, fname, ylabel):
    piv = s.pivot_table(index="year", columns="sector", values=flow_col, aggfunc="sum").fillna(0)
    piv = piv.loc[2015:2024]
    share = piv.div(piv.sum(axis=1), axis=0) * 100
    other = share.drop(columns=[c for c in keep if c in share.columns]).sum(axis=1)
    plot = share[[c for c in keep if c in share.columns]].copy()
    plot["Other"] = other
    palette = ["#303030", "#555555", "#777777", "#999999", "#bbbbbb",
               "#d0d0d0", "#e0e0e0", "#eeeeee"]
    fig, ax = plt.subplots(figsize=(7, 4.2))
    ax.stackplot(plot.index, plot.T.values,
                 labels=[c.replace("_", "/") for c in plot.columns],
                 colors=palette[:plot.shape[1]], alpha=0.9)
    ax.axvspan(COVID[0], COVID[1], color="#000000", alpha=0.10, zorder=5)
    style_ax(ax, ylabel)
    ax.set_xticks(plot.index)
    ax.set_xlim(2015, 2024)
    ax.set_ylim(0, 100)
    ax.legend(frameon=False, loc="center left", bbox_to_anchor=(1.01, 0.5))
    save(fig, fname)


composition("exports_bn",
            ["Metals_Minerals", "Energy", "Chemicals", "Agriculture"],
            "pub_export_composition", "Share of exports to China (\\%)")
composition("imports_bn",
            ["Machinery_Electrical", "Vehicles", "Textiles", "Metals_Minerals", "Plastics_Rubber"],
            "pub_import_composition", "Share of imports from China (\\%)")

# ---- 6. structural shift (2023 reversal): exports vs imports crossover ------
fig, ax = plt.subplots(figsize=(7, 4.2))
covid_band(ax)
ax.plot(yr, t.exports_bn, color=NAVY, lw=2.0, marker="o", ms=4, label="Exports to China")
ax.plot(yr, t.imports_bn, color=RED, lw=2.0, ls="--", marker="s", ms=4, label="Imports from China")
ax.axvline(2023, color="black", lw=0.9, ls=":")
ax.annotate("2023 balance\nreversal", (2023, ax.get_ylim()[1]), xytext=(2020.6, 13.2),
            fontsize=9, color="#333",
            arrowprops=dict(arrowstyle="->", color="#666", lw=0.8))
style_ax(ax, "US\\$ billions")
ax.set_xticks(yr)
ax.set_ylim(0, None)
ax.legend(frameon=False, loc="upper left")
save(fig, "pub_structural_shift")

# ---- 7. China import penetration (share of KAZ world imports) --------------
panel = pd.read_stata(os.path.join(DTA, "kazakhstan_china_annual_trade_panel_2015_2024.dta"))
fig, ax = plt.subplots(figsize=(7, 4.2))
covid_band(ax)
ax.plot(panel.year, panel.chn_imp_share_pct, color=RED, lw=2.0, marker="s", ms=4,
        label="China share of KAZ imports")
ax.plot(panel.year, panel.chn_exp_share_pct, color=NAVY, lw=2.0, marker="o", ms=4,
        label="China share of KAZ exports")
style_ax(ax, "Share of Kazakhstan's world trade (\\%)")
ax.set_xticks(panel.year)
ax.set_ylim(0, None)
ax.legend(frameon=False, loc="upper left")
save(fig, "pub_china_penetration")

print("done")
