#!/usr/bin/env python3
"""Summarize China-trade concentration and TII period sensitivity.

Inputs are generated by analysis_v2/build_analysis.py from the vendored
World Bank WITS/UN Comtrade extracts. The outputs support the manuscript's
descriptive robustness tables; they do not estimate causal effects.
"""

from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DTA = ROOT / "analysis_v2" / "dta"

concentration = pd.read_stata(DTA / "kazakhstan_china_hs4_concentration_2015_2024.dta")
tii = pd.read_stata(DTA / "kazakhstan_china_trade_intensity_index_2015_2024.dta")

selected = concentration.loc[
    concentration["year"].isin([2015, 2019, 2022, 2023, 2024]),
    ["year", "exp_top5_pct", "exp_hhi", "imp_top5_pct", "imp_hhi"],
].copy()
selected.to_stata(DTA / "kazakhstan_china_concentration_selected_years.dta", write_index=False)

periods = [("2015-2019", 2015, 2019), ("2020-2022", 2020, 2022), ("2023-2024", 2023, 2024)]
rows = []
for label, start, end in periods:
    values = tii.loc[tii["year"].between(start, end), "tii"]
    rows.append(
        {
            "period": label,
            "mean_tii": values.mean(),
            "minimum_tii": values.min(),
            "maximum_tii": values.max(),
        }
    )
summary = pd.DataFrame(rows)
summary.to_stata(DTA / "kazakhstan_china_tii_period_sensitivity.dta", write_index=False)

print("=== HS4 concentration, Kazakhstan-China trade ===")
print(selected.round(3).to_string(index=False))
print("\n=== TII period sensitivity ===")
print(summary.round(3).to_string(index=False))
